### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by OxMarco** [richkmeli/Richkware#4]
Hi,
the project seems to have Apache standard license but most files contain a starting comment: 

```
 /*
  *      Copyright 2016 Riccardo Melioli. All Rights Reserved.
  */
```

I think you should choose either to leave the copyright and replace Apache license with something else or to remove the heading comment from most source files.

**Comment by richkmeli** [comment]
Hi, thanks for your advice. i will change the notice to  `  Copyright {yyyy} {name of copyright owner}` in accordance with [Apache Standard Licence](https://github.com/richkmeli/Richkware/blob/master/LICENSE).
